UART peripheral module
kammce/Motherboard pull request #1
Opened 2018-07-25 02:54 UTC by vincentchu12

2018-07-26 00:39 UTC, kammce requested changes
Do you have a simulation for this file?

2018-07-26 00:39 UTC, kammce commented on src/Peripherals/UART.v
> +
Remove any extra lines in the file please.

2018-07-26 00:39 UTC, kammce commented on src/Peripherals/UART.v
> +endmodule
Add a newline character at the end of the file.

2018-07-26 00:41 UTC, kammce requested changes
Please also follow the file layout sections found in all other files.
This refers to the comments that block off each section of the file.

2018-08-10 05:09 UTC, vincentchu12 commented
Ready for a second review.

2019-09-15 18:33 UTC, closed without merging